version: '3.8'

services:
  flask_app:
    build: 
      context: .
      dockerfile: flask_app/Dockerfile
    container_name: flask_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - app_network
    command: python3 -u flask_app/run.py
  celery_worker:
    build: 
      context: .
      dockerfile: celery_work/Dockerfile
    container_name: celery_worker
    command: celery -A celery_work.celery.celery beat -l info
    depends_on:
      - redis
      - flask_app
    networks:
      - app_network
  redis:
    image: redis:latest
    networks:
      - app_network
  celery_beat:
    build: 
      context: .
      dockerfile: celery_work/Dockerfile
    container_name: celery_beat
    command: celery -A celery_work.celery.celery worker -l info
    depends_on:
      - redis
      - flask_app
    networks:
      - app_network

networks:
  app_network: