version: '3.8'

services:
  flask_app:
    build: 
      context: .
      dockerfile: flask_app/Dockerfile
    container_name: flask_app
    image: flask_app
    ports:
      - "80:80"
    environment:
      - MONGO_URI=${MONGO_URI}
      - my_client_id=${my_client_id}
      - my_client_secret=${my_client_secret}
    depends_on:
      - redis
      - celery_worker
    networks:
      - app_network
    command: python3 -um flask_app.run 
  
  celery_worker:
    build: 
      context: .
      dockerfile: celery_work/Dockerfile
    container_name: celery_worker
    image: celery_worker
    environment:
      - MONGO_IP=${MONGO_IP}
      - REDIS_IP=${REDIS_IP}
    depends_on:
      - redis
      - flask_app
    networks:
      - app_network
    command: celery -A celery_work.celery.celery worker -l info -B
    


# public.ecr.aws/peakon/redis:cluster-6.2.5
  redis:
    image: 'redis:7.0.11'
    networks:
      - app_network
    container_name: redis 
    
  # celery_beat:
  #   build: 
  #     context: .
  #     dockerfile: celery_work/Dockerfile
  #   container_name: celery_beat
  #   command: celery -A celery_work.celery.celery beat -l info
  #   depends_on:
  #     - redis
  #     - flask_app
  #   networks:
  #     - app_network

networks:
  app_network:

